### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by BlackRose01** [arrowhead-f/client-java-spring#15]
![error](https://user-images.githubusercontent.com/7542316/72244427-8babc480-35ee-11ea-8d86-18e525112fba.jpg)
Hello there,

I want to create a demonstrator for arrowhead with the skeleton. I added my relevant source code but when I start to compile there is always an error. I use IntelliJ as IDE.

The following ideas I tried:

- Added @EnableAutoConfiguration to ProviderMain.java
- Compiling the complete project instead of Provider only
- Update Version from dependencies
- Change POM.xml from provider regarding to [https://stackoverflow.com/questions/38792031/springboot-making-jar-files-no-auto-configuration-classes-found-in-meta-inf](https://stackoverflow.com/questions/38792031/springboot-making-jar-files-no-auto-configuration-classes-found-in-meta-inf)
- Move META-INF folder from /src/main to /src/main/resources or /src

`%d [%thread] %-5level %logger - %msg%n java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
        at org.springframework.util.Assert.notEmpty(Assert.java:464) ~[arrowhead-client-skeleton-provider.jar:?]
        at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getCandidateConfigurations(AutoConfigurationImportSelector.java:173) ~[arrowhead-client-skeleton-provider.jar:?]
        at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getAutoConfigurationEntry(AutoConfigurationImportSelector.java:116) ~[arrowhead-client-skeleton-provider.jar:?]
        at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector$AutoConfigurationGroup.process(AutoConfigurationImportSelector.java:396) ~[arrowhead-client-skeleton-provider.jar:?]
        at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGrouping.getImports(ConfigurationClassParser.java:874) ~[arrowhead-client-skeleton-provider.jar:?]
        at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.processGroupImports(ConfigurationClassParser.java:801) ~[arrowhead-client-skeleton-provider.jar:?]
        at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorHandler.process(ConfigurationClassParser.java:771) ~[arrowhead-client-skeleton-provider.jar:?]
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:188) ~[arrowhead-client-skeleton-provider.jar:?]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:325) ~[arrowhead-client-skeleton-provider.jar:?]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:242) ~[arrowhead-client-skeleton-provider.jar:?]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275) ~[arrowhead-client-skeleton-provider.jar:?]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95) ~[arrowhead-client-skeleton-provider.jar:?]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706) ~[arrowhead-client-skeleton-provider.jar:?]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532) ~[arrowhead-client-skeleton-provider.jar:?]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[arrowhead-client-skeleton-provider.jar:?]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [arrowhead-client-skeleton-provider.jar:?]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [arrowhead-client-skeleton-provider.jar:?]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [arrowhead-client-skeleton-provider.jar:?]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [arrowhead-client-skeleton-provider.jar:?]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [arrowhead-client-skeleton-provider.jar:?]
        at eu.arrowhead.client.skeleton.provider.ProviderMain.main(ProviderMain.java:21) [arrowhead-client-skeleton-provider.jar:?]
![error](https://user-images.githubusercontent.com/7542316/72243936-6bc7d100-35ed-11ea-800d-938dab1c9d50.jpg)
`

Atached you can find the error, too.

Thank you.

Best Regards,
BlackRose01

**Comment by borditamas** [comment]
According to your screen shot the Spring Boot version has been changed. The skeleton requires `2.1.5.RELEASE`.  Please verify your version in the parent pom.

**Comment by BlackRose01** [comment]
Ok. I solved the problem on my own. The problem was that I build the Artifact with the Build Menu in IntelliJ but I have to use the Maven Menu. Here is an instruction for people with the same problem:

- find the Maven menu (View -> Tool Windows -> Maven)
- select in the menu your module
- then go to lifecycle and click on install
